### ISSUE TITLE
Implement vibration extension function

### ISSUE THREAD

**Issue by nutyworks** [rockphin/gyeonhae-android#32]

**Comment by Gijuno** [comment]
`val vibrator = getSystemService(Context.VIBRATOR_SERVICE) as Vibrator
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            vibrator.vibrate(VibrationEffect.createWaveform(longArrayOf(100,1000,500,1000), -1))
        }
        else {
            vibrator.vibrate(3000)
        }`
